#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Mark Stenglein <mark@stengle.in>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Source all zsh files at ~/.config/zsh/post-zshrc.d
#
# This allows for some modularity in my Dotbot configuration.
if [[ -s "$HOME/.config/zsh/post-zshrc.d" ]]; then
  for f in $HOME/.config/zsh/post-zshrc.d/*.sh; do
    source "$f"
  done
fi

#
# Color Output
#
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'

export TERM=xterm-256color

